// Generates src/components/ui/icon-paths.ts from the installed lucide-react package, so the eleven
// icons the design uses are plain SVG in the markup and the library stays out of the client bundle.
// Run after changing the icon list or upgrading lucide-react: node scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";

const NAMES = [
  "arrow-up-right", "compass", "droplets", "file-badge", "gem", "key-round",
  "scale", "scroll-text", "shield-check", "truck", "x",
];

const version = JSON.parse(readFileSync("node_modules/lucide-react/package.json", "utf8")).version;
const out = [];
for (const name of NAMES) {
  const mod = await import(`../node_modules/lucide-react/dist/esm/icons/${name}.mjs`);
  const nodes = mod.__iconData.node.map(([tag, attrs]) => {
    const { key, ...rest } = attrs;
    return [tag, rest];
  });
  out.push(`  ${JSON.stringify(name)}: ${JSON.stringify(nodes)},`);
}

writeFileSync(
  "src/components/ui/icon-paths.ts",
  `// Generated by scripts/gen-icons.mjs from lucide-react ${version} (ISC licence). Do not edit by hand.\n` +
    `// Lucide's own artwork, inlined so the library is not shipped to the browser for eleven icons.\n\n` +
    `export const ICON_PATHS = {\n${out.join("\n")}\n} as const;\n\n` +
    `export type IconName = keyof typeof ICON_PATHS;\n`,
);
console.log(`icon-paths.ts written from lucide-react ${version}: ${NAMES.length} icons`);
