# Traces the MAY BACH lock-up (mb-br-01.png) into clean filled SVG paths and writes:
#   public/brand/wordmark.svg      - "MAY BACH" (Latin line)
#   public/brand/wordmark-ar.svg   - Arabic line
#   public/brand/lockup.svg        - full lock-up as traced
#   src/components/brand/paths.ts  - the same path data for inline React SVGs
# The emblem (mb-br-02.png) is redrawn geometrically as strokes in Emblem.tsx / public/brand/emblem.svg
# so the preloader can animate stroke-dashoffset. Masters are never modified.
import cv2, numpy as np, json, sys
from PIL import Image

src = 'public/images/mb-br-01.png'
im = np.array(Image.open(src).convert('RGBA'))
mask = ((im[:, :, 3] > 128).astype(np.uint8)) * 255
H, W = mask.shape

rows = mask.sum(axis=1) > 0
bands = []; start = None
for y, v in enumerate(rows):
    if v and start is None: start = y
    if not v and start is not None: bands.append([start, y - 1]); start = None
if start is not None: bands.append([start, H - 1])
print('raw bands', bands, file=sys.stderr)
merged = []
for b in bands:
    if merged and b[0] - merged[-1][1] < 20: merged[-1][1] = b[1]
    else: merged.append(b)
print('bands', merged, file=sys.stderr)
assert len(merged) == 3, merged
arabic, emblem, latin = merged

def trace(y0, y1, eps=1.1):
    crop = mask[y0:y1 + 1, :]
    xs = np.where(crop.sum(axis=0) > 0)[0]
    x0, x1 = int(xs.min()), int(xs.max())
    crop = crop[:, x0:x1 + 1]
    contours, hier = cv2.findContours(crop, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
    d = []
    for c in contours:
        if cv2.contourArea(c) < 30: continue
        c = cv2.approxPolyDP(c, eps, True).reshape(-1, 2)
        pts = ' '.join(f'{p[0]:.1f} {p[1]:.1f}' for p in c)
        d.append(f'M{pts}Z')
    w, h = x1 - x0 + 1, y1 - y0 + 1
    return ' '.join(d), w, h, x0, y0

def svg(d, w, h):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" fill="currentColor" fill-rule="evenodd">'
            f'<path d="{d}"/></svg>\n')

out = {}
for name, (y0, y1) in (('latin', latin), ('arabic', arabic), ('lockup', (merged[0][0], merged[-1][1]))):
    d, w, h, x0, y0_ = trace(y0, y1)
    out[name] = {'d': d, 'w': w, 'h': h}
    fn = {'latin': 'wordmark.svg', 'arabic': 'wordmark-ar.svg', 'lockup': 'lockup.svg'}[name]
    open(f'public/brand/{fn}', 'w', encoding='utf-8').write(svg(d, w, h))
    print(name, w, h, len(d), file=sys.stderr)

ts = ('// Generated by scripts/trace-brand.py from public/images/mb-br-01.png. Do not edit by hand.\n'
      'export const WORDMARK = ' + json.dumps({'d': out['latin']['d'], 'w': out['latin']['w'], 'h': out['latin']['h']}) + ' as const;\n'
      'export const WORDMARK_AR = ' + json.dumps({'d': out['arabic']['d'], 'w': out['arabic']['w'], 'h': out['arabic']['h']}) + ' as const;\n'
      'export const LOCKUP = ' + json.dumps({'d': out['lockup']['d'], 'w': out['lockup']['w'], 'h': out['lockup']['h']}) + ' as const;\n')
open('src/components/brand/paths.ts', 'w', encoding='utf-8').write(ts)
